name: Continuous Integration

# Trigger for all branches which are not workflow-managed
on: 
  push:
    branches-ignore: [gh-pages]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false # only want to validate this commit
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}